#!/bin/sh

[ -d '/var/cache/backlight/' ] || mkdir -p '/var/cache/backlight/'
[ -w '/var/cache/backlight/' ] || chmod 755 '/var/cache/backlight/'

for card in $(find /sys/class/backlight/ -type l); do
    cat "$card/brightness" > "/var/cache/backlight/$(basename "$card")-brightness-old"
done